---

- hosts: all
  sudo: yes
  tasks:
    - name: Installing pip
      package:
        name: "python-pip"
        state: present

- hosts: all
  sudo: yes
  roles:
    - weareinteractive.vsftpd
  vars:
    vsftpd_service_enabled: yes
    vsftpd_service_state: started
    vsftpd_users:
      - username: ftpuser
        name: FTP User
        password: "{{ 'ftpuser' | password_hash('sha256', 'mysecretsalt') }}"
    vsftpd_config:
       local_enable: 'YES'
       write_enable: 'YES'
       pasv_enable: 'YES'
       pasv_min_port: 10090
       pasv_max_port: 10100
       local_umask: '022'
       chroot_local_user: YES
       chroot_list_enable: 'YES'
       allow_writeable_chroot: 'YES'
       chroot_list_file: '/etc/vsftpd.chroot_list'
   - tasks:
       - name: create chroot list
         shell: touch /etc/vsftpd.chroot_list